version: '3.8'

services:
  app:
    build:
      context: .
      target: development # Dockerfile의 development 스테이지만 사용
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # node_modules는 마운트에서 제외하여 컨테이너의 것을 사용
    command: npm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      # 실제 프로덕션에서는 비밀번호를 직접 코드에 넣지 마세요.
      # Docker Secrets나 다른 방법을 사용하는 것이 좋습니다.
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=bs_db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bs_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
